package main

import (
	"fmt"
	"log"

	_ "workout_ledger/docs"
	"workout_ledger/internal/config"
	// Swagger docs (generated by `swag init`).
	//
	// NOTE: The generated `workout_ledger/docs` package is imported via a separate
	// build-tagged file (see `docs_import_swagger.go`) so builds don't fail when
	// docs aren't generated.
)

// @title           Workout Ledger API
// @version         1.0
// @description     Simple REST API for Workout Ledger.
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @BasePath        /
func main() {

	//TIP <p>Press <shortcut actionId="ShowIntentionActions"/> when your caret is at the underlined text
	// to see how GoLand suggests fixing the warning.</p><p>Alternatively, if available, click the lightbulb to view possible fixes.</p>
	s := "gopher"
	fmt.Printf("Hello and welcome, %s!\n", s)

	for i := 1; i <= 5; i++ {
		//TIP <p>To start your debugging session, right-click your code in the editor and select the Debug option.</p> <p>We have set one <icon src="AllIcons.Debugger.Db_set_breakpoint"/> breakpoint
		// for you, but you can always add more by pressing <shortcut actionId="ToggleLineBreakpoint"/>.</p>
		fmt.Println("i =", 100/i)
	}

	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	// App constructor lives in internal/config.
	a, err := config.New(cfg)
	if err != nil {
		log.Fatalf("app: %v", err)
	}

	log.Printf("listening on %s", cfg.HTTPAddress)
	if err := a.Run(); err != nil {
		log.Fatalf("run: %v", err)
	}

}
