CREATE TABLE IF NOT EXISTS "auth_refresh_tokens" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"token_hash" TEXT NOT NULL UNIQUE,
	"issued_at" TIMESTAMPTZ NOT NULL,
	"expires_at" TIMESTAMPTZ NOT NULL,
	"revoked_at" TIMESTAMPTZ,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	PRIMARY KEY("id")
);

CREATE INDEX "idx_auth_refresh_tokens_user_id"
ON "auth_refresh_tokens" ("user_id");

CREATE INDEX "idx_auth_refresh_tokens_token_hash"
ON "auth_refresh_tokens" ("token_hash");

ALTER TABLE "auth_refresh_tokens"
ADD FOREIGN KEY("user_id") REFERENCES "param_users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
