CREATE TABLE IF NOT EXISTS "param_users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"email" TEXT NOT NULL UNIQUE,
	"email_verified_at" TIMESTAMPTZ,
	"display_name" TEXT,
	"avatar_url" TEXT,
	"status" TEXT NOT NULL DEFAULT 'ACTIVE',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	"updated_at" TIMESTAMPTZ,
	"last_login_at" TIMESTAMPTZ,
	"password_hash" TEXT,
	"auth_provider" TEXT NOT NULL DEFAULT 'GOOGLE',
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "user_passwords" (
	"user_id" INTEGER NOT NULL UNIQUE,
	"password_hash" TEXT NOT NULL,
	"hash_version" INTEGER NOT NULL,
	"password_updated_at" TIMESTAMPTZ NOT NULL,
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "auth_provider" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"provider_name" TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "auth_identities" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"auth_provider_id" INTEGER NOT NULL,
	"provider_user_id" TEXT,
	"email_at_provider" TEXT,
	PRIMARY KEY("id")
);


CREATE INDEX "idx_user_id"
ON "auth_identities" ("user_id");
CREATE INDEX "idx_auth_provider_id"
ON "auth_identities" ("auth_provider_id");
CREATE UNIQUE INDEX "uq_auth_provider_user"
ON "auth_identities" ("auth_provider_id", "provider_user_id");

CREATE TABLE IF NOT EXISTS "param_workout" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"workout_name" TEXT NOT NULL,
	"rest_between_sets" INTERVAL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "param_exercise" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"exercise_name" TEXT NOT NULL,
	"icon_url" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "exercises_in_workout" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"param_exercise_id" INTEGER NOT NULL,
	"param_workout_id" INTEGER NOT NULL,
	"default_sets" SMALLINT,
	"default_rest" INTERVAL,
	"default_reps" SMALLINT,
	"order_index" SMALLINT NOT NULL CHECK(order_index >= 0),
	PRIMARY KEY("id")
);


CREATE UNIQUE INDEX "exercises_in_workout_index_0"
ON "exercises_in_workout" ("param_workout_id", "order_index");

CREATE TABLE IF NOT EXISTS "param_weight" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"exercises_in_workout_id" INTEGER NOT NULL,
	"param_set_type_id" INTEGER NOT NULL,
	"weight" NUMERIC(6,2) NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "param_set_type" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"set_type" TEXT NOT NULL DEFAULT 'PRIMARY',
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "data_workout" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"param_workout_id" INTEGER NOT NULL,
	"start_date_time" TIMESTAMPTZ NOT NULL,
	"end_date_time" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "data_exercise" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"param_exercise_id" INTEGER NOT NULL,
	"data_workout_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "idx_data_exercise_data_workout_id"
ON "data_exercise" ("data_workout_id");

CREATE TABLE IF NOT EXISTS "data_sets" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"data_exercise_id" INTEGER NOT NULL,
	"set_number" INTEGER NOT NULL,
	"reps_in_set" INTEGER NOT NULL,
	PRIMARY KEY("id")
);


CREATE UNIQUE INDEX "UNIQUE_SETS"
ON "data_sets" ("set_number", "data_exercise_id");
CREATE INDEX "idx_data_sets_data_exercise_id"
ON "data_sets" ("data_exercise_id");

CREATE TABLE IF NOT EXISTS "data_weight" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"data_sets_id" INTEGER NOT NULL,
	"weight" NUMERIC(6,2) NOT NULL,
	"param_set_type_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);


CREATE INDEX "idx_data_weight_data_sets_id"
ON "data_weight" ("data_sets_id");

CREATE TABLE IF NOT EXISTS "auth_refresh_tokens" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"token_hash" TEXT NOT NULL UNIQUE,
	"issued_at" TIMESTAMPTZ NOT NULL,
	"expires_at" TIMESTAMPTZ NOT NULL,
	"revoked_at" TIMESTAMPTZ,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
	PRIMARY KEY("id")
);


CREATE INDEX "idx_auth_refresh_tokens_user_id"
ON "auth_refresh_tokens" ("user_id");
CREATE INDEX "idx_auth_refresh_tokens_token_hash"
ON "auth_refresh_tokens" ("token_hash");
ALTER TABLE "data_exercise"
ADD FOREIGN KEY("param_exercise_id") REFERENCES "param_exercise"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_passwords"
ADD FOREIGN KEY("user_id") REFERENCES "param_users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "auth_identities"
ADD FOREIGN KEY("user_id") REFERENCES "param_users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "auth_identities"
ADD FOREIGN KEY("auth_provider_id") REFERENCES "auth_provider"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "param_workout"
ADD FOREIGN KEY("user_id") REFERENCES "param_users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "exercises_in_workout"
ADD FOREIGN KEY("param_exercise_id") REFERENCES "param_exercise"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "exercises_in_workout"
ADD FOREIGN KEY("param_workout_id") REFERENCES "param_workout"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "param_weight"
ADD FOREIGN KEY("exercises_in_workout_id") REFERENCES "exercises_in_workout"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "param_weight"
ADD FOREIGN KEY("param_set_type_id") REFERENCES "param_set_type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "data_workout"
ADD FOREIGN KEY("user_id") REFERENCES "param_users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "data_workout"
ADD FOREIGN KEY("param_workout_id") REFERENCES "param_workout"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "data_sets"
ADD FOREIGN KEY("data_exercise_id") REFERENCES "data_exercise"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "data_weight"
ADD FOREIGN KEY("data_sets_id") REFERENCES "data_sets"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "data_weight"
ADD FOREIGN KEY("param_set_type_id") REFERENCES "param_set_type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "data_exercise"
ADD FOREIGN KEY("data_workout_id") REFERENCES "data_workout"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "auth_refresh_tokens"
ADD FOREIGN KEY("user_id") REFERENCES "param_users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;